apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/BillyMichael/LDP.git
        revision: HEAD
        files:
          - path: "platform-apps/**/values.yaml"
  template:
    metadata:
      # Escape for Helm, will be processed by ArgoCD
      name: '{{ `{{ index .path.segments 2 }}` }}'
      annotations:
        # Sync waves:
        #   -1: CRD providers (must exist before CRs can be created)
        #    0: Auth services (authelia, lldap) - needed for OIDC discovery
        #    1: Apps that configure OIDC at startup (gitea, backstage, kargo)
        argocd.argoproj.io/sync-wave: '{{ `{{- $app := index .path.segments 2 -}}
          {{- $crdProviders := list "cert-manager" "external-secrets" "crossplane" -}}
          {{- $oidcClients := list "gitea" "backstage" "kargo" -}}
          {{- if has $app $crdProviders -}}-1{{- else if has $app $oidcClients -}}1{{- else -}}0{{- end -}}` }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/BillyMichael/LDP.git
        targetRevision: main
        path: '{{ `{{ .path.path }}` }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ `{{ index .path.segments 1 }}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m