lldap-chart:
  podAnnotations:
    reloader.stakater.com/auto: "true"
  secret:
    create: false
    useExisting: true
    name: lldap-credentials
  ingress:
    enabled: false
  hpa:
    enabled: false