apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: traefik
  description: The Cloud Native Application Proxy.
spec:
  type: infrastructure
  lifecycle: production
  owner: maintainers
  system: core
  dependsOn:
    - component:default/cert-manager
